#!/bin/bash

# ftx

# Returns single-byte indicator for file type (like ls -F) and shows the source of a symlink.

set -eu
IFS="$(printf '\n\t')"

for filename in "$@"; do

	if [[ -L $filename ]]; then					#link
		echo -e "$(echo $filename | sed 's/ /\\ /g')@ -> $(readlink $filename | sed 's/ /\\ /g')"

	elif [[ -d $filename ]]; then					#directory
		echo -e "$(echo $filename | sed 's/ /\\ /g')/"

	elif [[ -x $filename ]]; then					#executable
		echo -e "$(echo $filename | sed 's/ /\\ /g')*"

	elif [[ -p $filename ]]; then					#pipe
		echo -e "$(echo $filename | sed 's/ /\\ /g')|"

	elif [[ -S $filename ]]; then					#socket
		echo -e "$(echo $filename | sed 's/ /\\ /g')="

	elif [[ -f $filename ]]; then					#regular file
		echo -e "$(echo $filename | sed 's/ /\\ /g')"

	else
		echo -e "$(echo $filename | sed 's/ /\\ /g')?"		#unknown

	fi
done

exit 0
